### ISSUE TITLE
Library broken: Sending ListCommand failed: invalid server response

### ISSUE THREAD

**Issue by NovaPhoenix** [Difegue/Stylophone#10]
When viewing my library using MPD 0.21.9, I get this error:
```
MpcNET.Message.ErrorMpdMessage`1[System.COllections.Generic.List`1[System.String]].
```
![image](https://user-images.githubusercontent.com/25039349/95080320-93138080-06dd-11eb-95e2-0d526842bd6f.png)

**Comment by Difegue** [comment]
This was due to a small oversight in the MPD response decoding part.  
I kinda wonder why it only happens with the Windows server, but it should be fixed now. ¯\_(ツ)_/¯  

I'll try getting a build pushed to the Store later today.
