### ISSUE TITLE
invalid outputs parsing

### ISSUE THREAD

**Issue by grobian** [Difegue/Stylophone#100]
MPDnet isn't open for bugs, so doing it here, since Stylophone is the one barking in the end...

https://github.com/Difegue/MpcNET/blob/ddd090c6d0ccd116696043c8b32b44a831f148e8/Sources/MpcNET/Commands/Output/OutputsCommand.cs#L38C86-L38C87

This seems to assume one can walk in pairs of 4, but this simply isn't correct.  It's more like 5 if you exclude attributes:
https://mpd.readthedocs.io/en/latest/protocol.html#command-outputs 

However, why not look through these, and restart on `outputid`?

**Comment by grobian** [comment]
Sorry this is an owntone issue, looking at https://github.com/MusicPlayerDaemon/MPD/blob/9ff8e02e543ede2b1964e5ea3f26f00bf2ff90ec/src/output/Print.cxx#L21 it seems the output set is fixed indeed (apart from attributes).
It's brittle parsing though, assuming this is the case, so a mere suggestion to change it anyway.

**Comment by Difegue** [comment]
I remember already updating this inherited code once to parse by pairs of 4 instead of 3 because of an added attribute... 
Using `outputid` as a delimiter makes sense, although yeah it's not broken so I'll likely leave it as-is for now 😩  

Thanks for the notice though!

**Comment by grobian** [comment]
FWIW it's broken with owntone's MPD server, because it sends an invalid extra key, but I'm trying to address that with owntone right now so the error disappears on Stylophone's side.

**Comment by Difegue** [comment]
I've also enabled issues on the MpcNET fork, so feel free to post over there if you wish. 👍

**Comment by grobian** [comment]
filed the first issue there as reminder :)
