### ISSUE TITLE
library

### ISSUE THREAD

**Issue by senolfndk** [Difegue/Stylophone#18]
the library is not created

**Comment by senolfndk** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/52818836/104807301-0d7c9200-57ef-11eb-895f-f82caa843092.jpg)

**Comment by Difegue** [comment]
👋 Hello, and thanks for coming all the way here to file an issue. 😁
Do you have an MPD server correctly running ? And if so, is the Stylophone client connected to it in the Settings pane ?

**Comment by senolfndk** [comment]
no

Windows 10 için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: Difegue<mailto:notifications@github.com>
Gönderilme: 16 Ocak 2021 Cumartesi 18:34
Kime: Difegue/Stylophone<mailto:Stylophone@noreply.github.com>
Bilgi: şenol fındık<mailto:parantezz_34@hotmail.com>; State change<mailto:state_change@noreply.github.com>
Konu: Re: [Difegue/Stylophone] library (#18)


👋 Hello, and thanks for coming all the way here to file an issue. 😁
Do you have an MPD server correctly running ? And if so, is the Stylophone client connected to it in the Settings pane ?

**Comment by Difegue** [comment]
I see. This app only works if you have a matching MPD server, otherwise it'll just be empty and unusable as you've seen. 😅  
Check https://www.musicpd.org/ for more info if you're interested.

**Comment by senolfndk** [comment]
So how can I run the application, what should I do?

Windows 10 için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: Difegue<mailto:notifications@github.com>
Gönderilme: 16 Ocak 2021 Cumartesi 21:10
Kime: Difegue/Stylophone<mailto:Stylophone@noreply.github.com>
Bilgi: şenol fındık<mailto:parantezz_34@hotmail.com>; State change<mailto:state_change@noreply.github.com>
Konu: Re: [Difegue/Stylophone] library (#18)


I see. This app only works if you have a matching MPD server, otherwise it'll just be empty and unusable as you've seen. 😅
Check https://www.musicpd.org/ for more info if you're interested.

**Comment by senolfndk** [comment]
Can you connect remotely and help?

Windows 10 için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: Difegue<mailto:notifications@github.com>
Gönderilme: 16 Ocak 2021 Cumartesi 21:10
Kime: Difegue/Stylophone<mailto:Stylophone@noreply.github.com>
Bilgi: şenol fındık<mailto:parantezz_34@hotmail.com>; State change<mailto:state_change@noreply.github.com>
Konu: Re: [Difegue/Stylophone] library (#18)


I see. This app only works if you have a matching MPD server, otherwise it'll just be empty and unusable as you've seen. 😅
Check https://www.musicpd.org/ for more info if you're interested.

**Comment by senolfndk** [comment]
do you have teamviewer

Windows 10 için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: Difegue<mailto:notifications@github.com>
Gönderilme: 16 Ocak 2021 Cumartesi 21:10
Kime: Difegue/Stylophone<mailto:Stylophone@noreply.github.com>
Bilgi: şenol fındık<mailto:parantezz_34@hotmail.com>; State change<mailto:state_change@noreply.github.com>
Konu: Re: [Difegue/Stylophone] library (#18)


I see. This app only works if you have a matching MPD server, otherwise it'll just be empty and unusable as you've seen. 😅
Check https://www.musicpd.org/ for more info if you're interested.

**Comment by Difegue** [comment]
Sorry, I don't do remote support.  
If you don't already have a MPD server setup, I'm not sure this application is made for you, as specified in the description in the MS Store.

**Comment by senolfndk** [comment]
😥

Windows 10 için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: Difegue<mailto:notifications@github.com>
Gönderilme: 16 Ocak 2021 Cumartesi 23:04
Kime: Difegue/Stylophone<mailto:Stylophone@noreply.github.com>
Bilgi: şenol fındık<mailto:parantezz_34@hotmail.com>; State change<mailto:state_change@noreply.github.com>
Konu: Re: [Difegue/Stylophone] library (#18)


Sorry, I don't do remote support.
If you don't already have a MPD server setup, I'm not sure this application is made for you, as specified in the description in the MS Store.
