### ISSUE TITLE
Show friendly errors

### ISSUE THREAD

**Issue by gbraad** [Difegue/Stylophone#21]
In case of an error, please show a toast notification with the error... instead of a JSON dump:

![image](https://user-images.githubusercontent.com/1894/109601154-51d2b000-7b59-11eb-950f-1faebdffe582.png)

In this case the server had `playlist_directory` not set and the `ErrorMessage` and `MpdError` both contain the reason.

**Comment by gbraad** [comment]
Thanks. Will a new version be pushed to the store?

**Comment by Difegue** [comment]
Sure! I'm at least waiting on a stable 7.0 release for the Windows Community Toolkit to get the fix for #5 in.
