### ISSUE TITLE
Ability to toggle the retrival of cover images

### ISSUE THREAD

**Issue by luevano** [Difegue/Stylophone#26]
I'm running an mpd server on a VPS, I don't have cover images for all albums, and Stylophone keeps trying to retrieve them, which clutters the logs. A simple toggle would help, or the ability to add a different service to retrieve the cover images.

**Comment by Difegue** [comment]
Thanks for this report; It arrived a bit too late for me to put it in the upcoming v2, but I'll try to get it in for the next update. 👍

**Comment by Difegue** [comment]
Added in 2.1.
