### ISSUE TITLE
Question regarding Microsoft Store release schedule

### ISSUE THREAD

**Issue by 2ion** [Difegue/Stylophone#27]
I have previously purchased Stylophone through the Microsoft Store. v2 has been released on Github. Can you perhaps comment on how fast major updates can be expected to land in the store, if not fast with what kind of delay?

**Comment by Difegue** [comment]
👋 Normally MS Store updates release nearly at the same time as the tag lands on GitHub, v2 is a bit special since it's part of [Launch 2021](https://uwpcommunity.com/launch/).  

It'll launch on September 1st! Thanks for waiting. 🙏

**Comment by Difegue** [comment]
I've also written a blogpost about the changes in the upcoming version but haven't advertised it too much yet 😅  
https://tvc-16.science/stylophone-2.html

**Comment by 2ion** [comment]
Thank you for clarifying, that answers my question!
