### ISSUE TITLE
Backslashes in metadata stop album art from loading

### ISSUE THREAD

**Issue by cjohnsto-nz** [Difegue/Stylophone#35]
Have tested with Album name. If there is a backslash, album art doesn't load for that album, or any albums further down the list

**Comment by Difegue** [comment]
Couldn't repro.  
I did find and fix an issue in MpcNET with the search command and backslashes, but I don't think that was related. Maybe an issue with server encoding? 
![image](https://user-images.githubusercontent.com/8237712/150571317-15fbccab-3ca4-4d50-a177-3e19fcab3899.png)
