### ISSUE TITLE
Can't use a string hostname as the server address

### ISSUE THREAD

**Issue by connection-reset** [Difegue/Stylophone#39]
Stylophone 2.2.0 does not connect to my mpd server when I enter its hostname or IPv6 address, it fails with:

> Couldn't find an MPD server at this address!

When I enter the IPv4 address is connects immediately.

DNS works and resolves both IPv4 and IPv6 addresses. MPD listens on both addresses.

**Comment by Difegue** [comment]
Indeed, the underlying `TcpClient`s used by MpcNET were initialized with the old IPv4 config, so it makes sense IPv6 wouldn't work 😅  

I've modified the library code (https://github.com/Difegue/MpcNET/commit/6bcc61b57b6e3f16102868cce79ddbd2081cd389) to use dual mode sockets, so this should be solved in a future release.

**Comment by chowbok** [comment]
Specifying hostname still is not working. If this isn't an easy fix, then maybe just put a note in the dialog that it has to be an IP?

**Comment by Difegue** [comment]
Hmm I'm not sure if I've tried hostnames, the fix above was mostly for IPv6. Maybe hostnames aren't being translated to an `IPEndPoint` correctly! 
Might as well reopen this with a name change..

**Comment by Difegue** [comment]
Support for this should be available in the next update!
