### ISSUE TITLE
If queue ends and start a music again it delays and bugs out

### ISSUE THREAD

**Issue by rubynt** [Difegue/Stylophone#44]
If queue ends and start a music again it delays and bugs out

**Comment by Difegue** [comment]
👋 Needs a more detailed explanation, since as far as my test setup is concerned, playing a new track after a queue ends works fine. 🤷‍♂️  

Are you running a stock MPD server, or a derivative?

**Comment by rubynt** [comment]
I have a MPD server with httpd broadcasting, when i join the server with music playing everything works fine but after pausing it and start it a bit of the music what was in the queue plays and after that with a long delay starts to play the music. My httpd config is this
`
audio_output {
	type		"httpd"
	name		"My HTTP Stream"
	encoder		"flac"
	port		"8000"
	compression 	"0"
	quality		"9.0"			# do not define if bitrate is defined
	format		"48000:32:2"
	always_on       "yes"			# prevent MPD from disconnecting all listeners when playback is stopped
	max_clients	"0"			# optional 0=no limit
}
`

**Comment by Difegue** [comment]
Oh, you meant http stream playback is laggy? Shouldve specified that first 😅

Stream playback is mostly handled by libVLC and will always lag a bit behind the "real" playback, but we might not be resetting the stream correctly when hitting end of queue - - Worth investigating.

**Comment by rubynt** [comment]
I think you could implement it if the mpd sends signal that the music is started refresh the httpd stream and that could fix it i think

**Comment by rubynt** [comment]
Hey, I

**Comment by rubynt** [comment]
Hey, I didnt wanted to close this, i tried to figure out how to implement it but i dont know how to write c# and i dont know what style should it be written in. Can you please make a patch for when the queue ends the local player resets and when starts the local player starts?

**Comment by Difegue** [comment]
This'll be fixed in the next update. Thanks for the report!
