### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by panbf** [Difegue/Stylophone#49]
after running in background for a relatively long time, say 3-5 days, it will take up to 1.5G memory despite its low memory consumption (about 75m) at a fresh new start. this phenomenon can be reproduced everytime on my pc running windows 10 21h2 ver. 19044.1586 with the latest version (v. 2.2.0.0) of stylophone purchased via microsoft store. not sure if this is a general problem or just one of my own.

**Comment by panbf** [comment]
usually i will stay on the track info/now-playing page so that i can see what is now playing. hope this could be helpful in troubleshooting.

**Comment by panbf** [comment]
update: it has been just 9 hrs after i opened this issue above and the memory usage (commit size) reaches to more than 1G
![20220428154418](https://user-images.githubusercontent.com/87701508/165704602-00ad4fc8-4e1e-4998-a937-754c54a71be4.png)

**Comment by Difegue** [comment]
Thanks for the report -- I'll try to have a look later.  
In the meantime, can you try temporarily disabling the album art feature to see if that fixes the issue? I'm suspecting the leaks come from the SkiaSharp-managed cover art.

**Comment by panbf** [comment]
The workaround to  turn off the album art does help! Hope you can fix it in the next upgrade. I must say this is a great app and thank you for all the efforts!

**Comment by panbf** [comment]
The workaround to  turn off the album art does help! Hope you can fix it in the next upgrade. I must say this is a great app and thank you for all the efforts!

**Comment by Difegue** [comment]
woops, didn't mean to close the issue, I'll definitely try to fix this. Glad to know the cover art workaround helps! 🔥

**Comment by Difegue** [comment]
This'll be fixed in an upcoming update -- Thanks for the report!
