### ISSUE TITLE
Queue doesn't display upcoming songs

### ISSUE THREAD

**Issue by chowbok** [Difegue/Stylophone#64]
Seems like it doesn't happen all the time, but when I go to my queue, it's only displaying the current song and the songs that have already played, not the upcoming songs. The upcoming songs are indeed in my queue, I see them in other clients.

**Comment by Difegue** [comment]
👋 Is this using the stock MPD server? I've never seen this while using the app.  

I did push an update recently which fixed some bugs related to the queue view, so that might help.

**Comment by chowbok** [comment]
Yes, standard MPD. I don't see this behavior all the time, and I'm not sure yet how to reproduce it. I'll keep you posted.

**Comment by Difegue** [comment]
I've revamped the queue update mechanism in 2.6 (again), so I'll tentatively close this for now. Feel free to reopen if it still happens!
