### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by chowbok** [Difegue/Stylophone#68]
Well, I don't know what I did, but now when I add anything to the queue, the program crashes after adding it. Hopefully it's sending you traces... let me know if there's anything I need to do to help you debug this.

**Comment by Difegue** [comment]
I'm not seeing anything in App Center sadly - The MS Store dashboard does pick up your crashes, but they're coming up as "Unknown", which leads me to believe this is a deeper UWP/WinRT issue I can't really fix?  

I'd recommend resetting the app from Windows Settings and hopefully that fixes it -- Sorry I can't be more helpful on this one.

**Comment by chowbok** [comment]
Okay, resetting the settings has fixed it, at least for now.
