### ISSUE TITLE
Consider switching to .NET MAUI

### ISSUE THREAD

**Issue by leonardder** [Difegue/Stylophone#74]
[The new version of the .NET upgrade assistant](https://devblogs.microsoft.com/dotnet/upgrade-assistant-general-availability/) has support for migration from Xamarin to .NET MAUI as well as from UWP to WinUI. This should make it possible to uniformize the Windows and iOS experience of the app as well as add support for other platforms (like Android).

**Comment by Difegue** [comment]
The upgrade assistant only supports going from Xamarin.Forms to MAUI (which is its direct successor)  

The iOS version isn't built using Xamarin.Forms, but directly through Xamarin.iOS, which allows to me to directly use Interface Builder and stuff like that.  

I did try using [Forms](https://github.com/Difegue/Stylophone/tree/xamarinforms) first, but the result was kinda poor and I didn't care enough about android to go further with it 🤷
