### ISSUE TITLE
Local playback of remote server through mpd http stream

### ISSUE THREAD

**Issue by fn-ix** [Difegue/Stylophone#76]
Would like to see Stylophone have the ability to output audio directly through playing the remote mpd’s http stream. A feature like this exists for example in [Cantata](https://github.com/CDrummond/cantata).

A usecase would be using Stylophone as the sole music playback solution in an Xbox. At the moment, it’s only useful as an mpd controller, with another app needed to actually play the music from the stream.

**Comment by Difegue** [comment]
If your server has an httpd output, you should be able to use the Local Playback feature to do exactly this:  
![image](https://github.com/Difegue/Stylophone/assets/8237712/653bee0e-be4e-4eb8-89a7-87d4f07a5a7d)

**Comment by fn-ix** [comment]
Alright, didn’t know this feature already exists as it’s not listed on the readme.
