### ISSUE TITLE
App crashes when playing DSD files

### ISSUE THREAD

**Issue by chrisc2615** [Difegue/Stylophone#87]
Hardware:  Mercury Pi2 Streamer, 4Tb SSD connected USB

FLAC and WAV files play fine
Try a DSD file, plays for 1 second, then stops and app crashes

Is there a fix please?

Thanks

**Comment by Difegue** [comment]
👋 First time I'm hearing of DSD files -- Do you have an example I could try out?

**Comment by chrisc2615** [comment]
Did you receive the DSD file I emailed to you?

**Comment by Difegue** [comment]
No; You might want to attach it to this GH issue instead?

**Comment by chrisc2615** [comment]
[07 - Sting - Prelude To The End Of The Game.zip](https://github.com/Difegue/Stylophone/files/14111123/07.-.Sting.-.Prelude.To.The.End.Of.The.Game.zip)

**Comment by Difegue** [comment]
Thank you; I've identified that there's indeed a crash with the MpcNET client library when getting status for DSD files in particular.  

I have a fix in https://github.com/Difegue/MpcNET/commit/95eb2be4ea400527d6ba7ae27084d8993d63b873 which will be in the next release of the app.
