### ISSUE TITLE
Titles show in queue after queue cleared

### ISSUE THREAD

**Issue by WillerZ** [Difegue/Stylophone#88]
I see track names etc behind the "All is quiet now" messaging. Looks like maybe UI table row objects are being recycled and not cleared before reuse.

**Comment by WillerZ** [comment]
Attaching some screenshots so you can see what I'm talking about and to some extent verify whether I've done something weird.

Initial queue looks OK:

![image](https://github.com/Difegue/Stylophone/assets/509064/5fd1ab45-3592-4c2c-8a7f-5e35f8981c85)

After adding some songs looks OK:
![image](https://github.com/Difegue/Stylophone/assets/509064/b6cc48de-7ccb-4f99-9778-2a9a43de6545)

After clearing looks broken:
![image](https://github.com/Difegue/Stylophone/assets/509064/f2f48fed-a32b-4000-b491-47c21dd82c0e)

Interestingly I was still able to scroll the queue pane for a few seconds after clearing it, and that seems to be why the songs in the post-clearing screenshot don't match the ones in the pre-clearing screenshot.

**Comment by Difegue** [comment]
Weird, I'll look into this at some point. Thanks for the report!

**Comment by Difegue** [comment]
Can repro; I blame either WinUI or the toolkit on that one since things are cleaned up properly on the app side...  
It's easy to hide the grid in any case, shouldve probably done that to begin with.  

I'll have this fixed in the next release, thanks.
