### ISSUE TITLE
Unable to connect to local MPD server

### ISSUE THREAD

**Issue by NovaPhoenix** [Difegue/Stylophone#9]
Hey! I just found this app looking for a good MPD player on Windows (I too have used that old version of Cantata all this time) but it doesn't seem to be able to connect to my locally hosted MPD server, while Cantata and other clients can. Tested on MPD 0.22 and 0.21 Windows binaries.

**Comment by Difegue** [comment]
If your MPD server is locally hosted, you're probably running into the issue where UWP apps can't access localhost.  
(See https://stackoverflow.com/questions/33259763/uwp-enable-local-network-loopback/33263253#33263253 for a summary.)
There is a workaround you can use with checknetisolation which should work:  

```
checknetisolation loopbackexempt -a -n="13459Difegue.Stylophone_zd7bwy3j4yjfy"
```

**Comment by NovaPhoenix** [comment]
That worked! Though now I'm having another issue, should I open up a separate GH issue for this?
![image](https://user-images.githubusercontent.com/25039349/95035600-34251b80-068b-11eb-8841-35945aa69a1e.png)

**Comment by Difegue** [comment]
A separate issue would be good yeah, thanks.  
I suspect I'll have to try with a windows build on my end to try and repro the issue.

**Comment by Barbaross93** [comment]
Unfortunately, that workaround doesn't seem to work for me. Did the App container name change recently? I am running Windows 11 22H2 if that helps.
