### ISSUE TITLE
need setting to specify http stream (port) for local playback

### ISSUE THREAD

**Issue by grobian** [Difegue/Stylophone#94]
To e.g. run stylophone against owntune, a different local stream url needs to be used.  It would be great if the local stream url could be set manually, so one could do something like:

```
server: music.my.domain
port: 6600
local stream: https://music.my.domain/stream.mp3
```

But starting with a simple port number for the local stream would already be of some help!

Thanks

**Comment by Difegue** [comment]
👋 Making the local playback http port configurable is definitely in the cards, I just haven't gotten to it yet. Thanks!

**Comment by Difegue** [comment]
I'll have this available in a future release.
