### ISSUE TITLE
crash when selecting item from library too fast

### ISSUE THREAD

**Issue by grobian** [Difegue/Stylophone#98]
Go to Library, type something to search (first 2-3 characters), immediately select a match.  App will crash.

Only when waiting several seconds after the items have appeared, selecting them works.

**Comment by Difegue** [comment]
I suspect this is an iOS crash, but I did find something similar on Windows so I'm linking it here.  
I'll try to look at iOS too!

**Comment by grobian** [comment]
seems possible, I think it's loading albumart or other info or something, thanks

**Comment by Difegue** [comment]
I fixed the crash above that I could see once and haven't managed to reproduce the issue while debugging on my SE since.  

I'll tentatively mark this as fixed in the upcoming update.
